export const SOUND_FILES = {
    bgm_main: "bgSound.mp3",
    sfx_btn: "btn.mp3",
    sfx_click: "click.mp3",
    sfx_coin: "coin.mp3",
    sfx_win: "win.mp3",
    sfx_boom: "boom.mp3",
    // bgm_moria: "BGM_Moria.mp3",
    // bgm_argonath: "BGM_Argonath.mp3",
    // bgm_doom: "BGM_Doom.mp3",
    // bgm_freespin: "BGM_FreeSpin (option 1).mp3",
    // bgm_bonus: "bgm_bonus.mp3",
    // button_click_blevel: "SFX_Click.mp3",
    // button_click_spin: "SFX_Spin.mp3",
    // button_click_other: "SFX_Click.mp3",
    // button_turbo: "SFX_Click.mp3",
    // sfx_page: "SFX_Page.mp3",
    // sfx_rolling: "SFX_Reel.mp3",
    // sfx_stop: "SFX_Reel Stop.mp3",
    // sfx_win_low: "SFX_Low Win.mp3",
    // sfx_win_high: "SFX_Big Win.mp3",
    // sfx_winline: "SFX_Low Win.mp3",
    // sfx_tpf_wild: "SFX_Ring.mp3",
    // sfx_win_amount: "SFX_Count.mp3",
    // sfx_bigwin_amount: "SFX_Count.mp3",
    // sfx_bigwin_popup: "SFX_Big Win.mp3",
    // sfx_megawin: "sfx_megawin.m4a",
    // sfx_transition_freespin: "sfx_transitionfreespin.mp3",
    // sfx_ultrawin: "sfx_ultra.m4a",
    // sfx_jackpot: "sfx_jackpot.mp3",
    // sfx_hobbit: "SFX_Hobbit.mp3",
    // sfx_gimli: "SFX_Gimli.mp3",
    // sfx_legolas: "SFX_Legolas.mp3",
    // sfx_aragorn: "SFX_Aragorn.mp3",
    // sfx_gandalf: "SFX_Gandalf.mp3",
    // sfx_gollum: "SFX_Gollum.mp3",
    // sfx_saruman: "SFX_Saruman (opt 1).mp3",
    // sfx_knightdark: "SFX_KnightDark.mp3",
    // sfx_burden: "SFX_Burden.mp3",
    // sfx_breakfast: "SFX_Second Breakfast.mp3",
    // sfx_hunters: "SFX_3Hunter.mp3",
    // sfx_duel: "SFX_Wizard Duel.mp3",
    // sfx_bonus_lose: "SFX_Bonus Lose.mp3",
    // sfx_bonus_win: "SFX_Bonus Win.mp3",
    // sfx_safe: "sfx_safe.m4a",
    // sfx_fail: "fail.wav",
} as const;

export type SoundName = keyof typeof SOUND_FILES;
export const AUDIO_ALIASES = [...new Set(Object.values(SOUND_FILES))];

// export const SYMBOL_SOUNDS: Partial<Record<number, SoundName>> = {
//     5: "sfx_hobbit",
//     6: "sfx_hobbit",
//     7: "sfx_hobbit",
//     8: "sfx_hobbit",
//     9: "sfx_gimli",
//     10: "sfx_legolas",
//     11: "sfx_aragorn",
//     12: "sfx_gandalf",
//     13: "sfx_tpf_wild",
//     14: "sfx_gollum",
//     15: "sfx_saruman",
//     16: "sfx_knightdark",
// };
// export const LORE_SOUNDS: Partial<Record<string, SoundName>> = {
//     blade_in_the_dark: "sfx_knightdark",
//     burden_of_the_ring: "sfx_burden",
//     second_breakfast: "sfx_breakfast",
//     three_hunters: "sfx_hunters",
//     wizards_duel: "sfx_duel",
// };
